// Generated by scripts/generate-images.mjs - AI pictures for dishes and chefs.
// Dishes or chefs without a picture fall back to their 3D emoji.
export const DISH_PHOTOS: Record<string, number> = {};

export const CHEF_PHOTOS: Record<string, number> = {};
