// Generates the AI dish and chef pictures through the "Kitchy's image generator" n8n workflow,
// then rewrites lib/photos.ts so the app uses them. Pictures that already exist are skipped.
//
//   N8N_IMAGE_URL=https://<your>.app.n8n.cloud/webhook/<path> N8N_IMAGE_KEY=<secret> node scripts/generate-images.mjs
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';

const url = process.env.N8N_IMAGE_URL;
const key = process.env.N8N_IMAGE_KEY;
if (!url || !key) {
  console.error('Set N8N_IMAGE_URL and N8N_IMAGE_KEY first.');
  process.exit(1);
}

const prompts = JSON.parse(readFileSync(new URL('./image-prompts.json', import.meta.url)));
const root = new URL('../assets/photos/', import.meta.url);

for (const group of ['dishes', 'chefs']) {
  for (const [id, { prompt, size }] of Object.entries(prompts[group])) {
    const file = new URL(`${group}/${id}.png`, root);
    if (existsSync(file)) continue;
    process.stdout.write(`${group}/${id} ... `);
    const res = await fetch(url, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'x-kitchys-key': key },
      body: JSON.stringify({ prompt, size }),
    });
    const type = res.headers.get('content-type') ?? '';
    if (!res.ok || !type.startsWith('image/')) {
      console.log(`failed (${res.status}) ${await res.text()}`);
      process.exit(1);
    }
    writeFileSync(file, Buffer.from(await res.arrayBuffer()));
    console.log('done');
  }
}

// Rewrite the lookup table the app imports.
const entries = (group) =>
  readdirSync(new URL(`${group}/`, root))
    .filter((f) => /\.(png|jpe?g|webp)$/.test(f))
    .sort()
    .map((f) => `  '${f.replace(/\.\w+$/, '')}': require('@/assets/photos/${group}/${f}'),`)
    .join('\n');
writeFileSync(
  new URL('../lib/photos.ts', import.meta.url),
  `// Generated by scripts/generate-images.mjs - AI pictures for dishes and chefs.\n` +
    `// Dishes or chefs without a picture fall back to their 3D emoji.\n` +
    `export const DISH_PHOTOS: Record<string, number> = {\n${entries('dishes')}\n};\n\n` +
    `export const CHEF_PHOTOS: Record<string, number> = {\n${entries('chefs')}\n};\n`
);
console.log('Updated lib/photos.ts');
